### ISSUE TITLE
피드 조회

### ISSUE THREAD

**Issue by dmdgpdi** [DayByQuest/frontend#11]
## Feature Description
- 팔로우한 유저의 게시물과 추천 그룹을 조회할 수 있다.

## Todo list

- [x] 임시 데이터 활용해서 구현
- [x] 통신 서버와 연결

## Screenshots (Optional)

https://github.com/DayByQuest/frontend/assets/33450285/c84bb5fb-a5ff-4694-b8a3-4258a8c7b92a

## Additional Feature
- [ ] 에러 처리 
- [ ] 값이 없을 때의 로직 처리
