### ISSUE TITLE
그룹원 목록 조회

### ISSUE THREAD

**Issue by dmdgpdi** [DayByQuest/frontend#23]
## Feature Description
- 해당 그룹에 가입한 그룹원을 조회할 수 있다.

## Todo list

- [x] 통신 서버와 연결
 
## Screenshots (Optional)

https://github.com/DayByQuest/frontend/assets/33450285/fb9fbf62-bd72-4693-9650-0491e27e17db

## Additional Feature
- [x] 예외 처리 기능 추가
- [ ] 라우팅 기능 추가
