### ISSUE TITLE
검색

### ISSUE THREAD

**Issue by dmdgpdi** [DayByQuest/frontend#30]
## Feature Description
- 사용자의 username, 그룹명, 퀘스트명을 검색할 수 있다.

## Todo list

- [x] 통신 서버와 연결

## Screenshots (Optional)

https://github.com/DayByQuest/frontend/assets/33450285/e87d77ab-94ae-45c4-90ab-b30dbb4d889a

https://github.com/DayByQuest/frontend/assets/33450285/566b1251-5160-4de5-aaad-26462266f69a

## Additional Feature
- [x] 예외 처리 기능 추가
- [ ] 네비게이터로 이동한 뒤에 다시 돌아올 때, 변경점 적용 로직 구현
